nome = input("Digite seu nome: ")
sobrenome = input("Digite o seu sobrenome: ")
idade = input("Digite a sua idade: ")
altura = input("Digite a sua altura: ")
print("Nome completo: "+nome+" "+sobrenome)
print("Idade: "+idade+", altura: "+altura)
print("Tamanho do nome: %d"%(len(nome)))
print("Tamanho do sobrenome: %d"%(len(sobrenome)))
